name: Auto Build and Deployment

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 20.19.5
  PROJECT_NAME: ng-devtools

jobs:
  buildanddeploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: 'Use Node.js ${{ env.NODE_VERSION }}'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn run build
      - name: AWS Assume Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
      - name: Deploy to S3
        run: |
          aws s3 sync dist/${{ env.PROJECT_NAME }}/browser s3://${{ secrets.S3_BUCKET_NAME }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
